version: '3.8'

services:
  api:               #1. The API service(Node.js Application)
    build: ./api
    environment:
      - PORT=3001
      - DATABASE_URL=postgres://admin:password@postgres:5432/research_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy   # Wait until postgres passes health check
      redis:
        condition: service_started   # Just wait for redis to start
    restart: on-failure              # Auto-restart if api crashes

  # 2. Load Balancer service
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80" # Maps laptop port 8080 to Nginx's port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

  # 3. Monitoring Database service
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090" # we can view the UI at http://localhost:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  # 4. Monitoring Dashboard service
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3100:3000" 
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  # 5. Relational Database service
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=research_db
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data across restarts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d research_db"]
      interval: 5s    # Check every 5 seconds
      timeout: 5s     # Each check must respond within 5 seconds
      retries: 5      # Mark unhealthy after 5 consecutive failures

  # 6. Cache service
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data  # Persist cache across restarts

volumes:
  postgres_data:
  redis_data:
